// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/AlleksDev/ScoreUp-API/internal/core"

	userApp "github.com/AlleksDev/ScoreUp-API/internal/user/application"
	userInfra "github.com/AlleksDev/ScoreUp-API/internal/user/infrastructure"
	userAdapters "github.com/AlleksDev/ScoreUp-API/internal/user/infrastructure/adapters"
	userControllers "github.com/AlleksDev/ScoreUp-API/internal/user/infrastructure/controllers"
	userRepo "github.com/AlleksDev/ScoreUp-API/internal/user/infrastructure/repository"

	retoApp "github.com/AlleksDev/ScoreUp-API/internal/reto/application"
	retoInfra "github.com/AlleksDev/ScoreUp-API/internal/reto/infrastructure"
	retoControllers "github.com/AlleksDev/ScoreUp-API/internal/reto/infrastructure/controllers"
	retoRepo "github.com/AlleksDev/ScoreUp-API/internal/reto/infrastructure/repository"

	logroApp "github.com/AlleksDev/ScoreUp-API/internal/logro/application"
	logroInfra "github.com/AlleksDev/ScoreUp-API/internal/logro/infrastructure"
	logroControllers "github.com/AlleksDev/ScoreUp-API/internal/logro/infrastructure/controllers"
	logroRepo "github.com/AlleksDev/ScoreUp-API/internal/logro/infrastructure/repository"

	ulApp "github.com/AlleksDev/ScoreUp-API/internal/usuario_logro/application"
	ulInfra "github.com/AlleksDev/ScoreUp-API/internal/usuario_logro/infrastructure"
	ulAdapters "github.com/AlleksDev/ScoreUp-API/internal/usuario_logro/infrastructure/adapters"
	ulControllers "github.com/AlleksDev/ScoreUp-API/internal/usuario_logro/infrastructure/controllers"
	ulRepo "github.com/AlleksDev/ScoreUp-API/internal/usuario_logro/infrastructure/repository"

	urApp "github.com/AlleksDev/ScoreUp-API/internal/usuario_reto/application"
	urInfra "github.com/AlleksDev/ScoreUp-API/internal/usuario_reto/infrastructure"
	urAdapters "github.com/AlleksDev/ScoreUp-API/internal/usuario_reto/infrastructure/adapters"
	urControllers "github.com/AlleksDev/ScoreUp-API/internal/usuario_reto/infrastructure/controllers"
	urRepo "github.com/AlleksDev/ScoreUp-API/internal/usuario_reto/infrastructure/repository"
)

// Injectors from wire.go:

// InitializeApp wires all dependencies automatically.
// This code was GENERATED by Wire — do not edit manually.
func InitializeApp() (*App, error) {
	// ── Infraestructura base ──
	connMySQL, err := core.GetMySQLPool()
	if err != nil {
		return nil, err
	}

	// ── Feature: User ──
	userMySQLRepository := userRepo.NewUserMySQLRepository(connMySQL)
	bcryptAdapter := userAdapters.NewBcryptAdapter()
	jwtTokenAdapter := userAdapters.NewJWTTokenAdapter()
	createUser := userApp.NewCreateUser(userMySQLRepository, bcryptAdapter)
	loginUser := userApp.NewLoginUser(userMySQLRepository, bcryptAdapter, jwtTokenAdapter)
	getRank := userApp.NewGetRank(userMySQLRepository)
	createUserController := userControllers.NewCreateUserController(createUser)
	loginUserController := userControllers.NewLoginUserController(loginUser)
	getRankController := userControllers.NewGetRankController(getRank)
	userModule := userInfra.NewUserModule(createUserController, loginUserController, getRankController)

	// ── Feature: Reto ──
	retoMySQLRepository := retoRepo.NewRetoMySQLRepository(connMySQL)
	createReto := retoApp.NewCreateReto(retoMySQLRepository)
	getReto := retoApp.NewGetReto(retoMySQLRepository)
	updateReto := retoApp.NewUpdateReto(retoMySQLRepository)
	deleteReto := retoApp.NewDeleteReto(retoMySQLRepository)
	createRetoController := retoControllers.NewCreateRetoController(createReto)
	getRetoController := retoControllers.NewGetRetoController(getReto)
	updateRetoController := retoControllers.NewUpdateRetoController(updateReto)
	deleteRetoController := retoControllers.NewDeleteRetoController(deleteReto)
	retoModule := retoInfra.NewRetoModule(createRetoController, getRetoController, updateRetoController, deleteRetoController)

	// ── Feature: Logro ──
	logroMySQLRepository := logroRepo.NewLogroMySQLRepository(connMySQL)
	createLogro := logroApp.NewCreateLogro(logroMySQLRepository)
	getLogro := logroApp.NewGetLogro(logroMySQLRepository)
	updateLogro := logroApp.NewUpdateLogro(logroMySQLRepository)
	deleteLogro := logroApp.NewDeleteLogro(logroMySQLRepository)
	createLogroController := logroControllers.NewCreateLogroController(createLogro)
	getLogroController := logroControllers.NewGetLogroController(getLogro)
	updateLogroController := logroControllers.NewUpdateLogroController(updateLogro)
	deleteLogroController := logroControllers.NewDeleteLogroController(deleteLogro)
	logroModule := logroInfra.NewLogroModule(createLogroController, getLogroController, updateLogroController, deleteLogroController)

	// ── Feature: UsuarioLogro ──
	usuarioLogroMySQLRepository := ulRepo.NewUsuarioLogroMySQLRepository(connMySQL)
	userQueryAdapter := ulAdapters.NewUserQueryAdapter(connMySQL)
	retoQueryAdapter := ulAdapters.NewRetoQueryAdapter(connMySQL)
	logroQueryAdapter := ulAdapters.NewLogroQueryAdapter(connMySQL)
	evaluateLogros := ulApp.NewEvaluateLogros(usuarioLogroMySQLRepository, userQueryAdapter, retoQueryAdapter, logroQueryAdapter)
	getUsuarioLogros := ulApp.NewGetUsuarioLogros(usuarioLogroMySQLRepository)
	deleteUsuarioLogro := ulApp.NewDeleteUsuarioLogro(usuarioLogroMySQLRepository)
	evaluateLogrosController := ulControllers.NewEvaluateLogrosController(evaluateLogros)
	getUsuarioLogrosController := ulControllers.NewGetUsuarioLogrosController(getUsuarioLogros)
	deleteUsuarioLogroController := ulControllers.NewDeleteUsuarioLogroController(deleteUsuarioLogro)
	usuarioLogroModule := ulInfra.NewUsuarioLogroModule(evaluateLogrosController, getUsuarioLogrosController, deleteUsuarioLogroController)

	// ── Feature: UsuarioReto ──
	usuarioRetoMySQLRepository := urRepo.NewUsuarioRetoMySQLRepository(connMySQL)
	urUserScoreAdapter := urAdapters.NewUserScoreAdapter(connMySQL)
	urRetoQueryAdapter := urAdapters.NewRetoQueryAdapter(connMySQL)
	logroEvaluatorAdapter := urAdapters.NewLogroEvaluatorAdapter(evaluateLogros)
	joinReto := urApp.NewJoinReto(usuarioRetoMySQLRepository)
	updateProgress := urApp.NewUpdateProgress(usuarioRetoMySQLRepository, urRetoQueryAdapter, urUserScoreAdapter, logroEvaluatorAdapter)
	getUsuarioRetos := urApp.NewGetUsuarioRetos(usuarioRetoMySQLRepository)
	leaveReto := urApp.NewLeaveReto(usuarioRetoMySQLRepository)
	joinRetoController := urControllers.NewJoinRetoController(joinReto)
	updateProgressController := urControllers.NewUpdateProgressController(updateProgress)
	getUsuarioRetosController := urControllers.NewGetUsuarioRetosController(getUsuarioRetos)
	leaveRetoController := urControllers.NewLeaveRetoController(leaveReto)
	usuarioRetoModule := urInfra.NewUsuarioRetoModule(joinRetoController, updateProgressController, getUsuarioRetosController, leaveRetoController)

	// ── Composición final ──
	engine := ProvideGinEngine(userModule, retoModule, logroModule, usuarioRetoModule, usuarioLogroModule)
	app := NewApp(engine)
	return app, nil
}
